apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  namespace: default
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: grc.io/kuar-demo/kuard-amd64:1
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 3
    volumeMounts:
    - name: cache
      mountPath: /cache
  volumes:
  - name: cache
    emptyDir: {}